import work.lclpnet.build.task.GithubDeploymentTask

plugins {
	id 'fabric-loom' version '1.10-SNAPSHOT'
	id 'maven-publish'
	id 'gradle-build-utils' version '1.7.0'
    id 'com.modrinth.minotaur' version '2.4.3'
    id "me.champeau.jmh" version '0.7.3'
    id "io.morethan.jmhreport" version "0.9.0"
}

Properties props = buildUtils.loadProperties('publish.properties')

version = "${project.mod_version}+${project.minecraft_version}"
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    maven {
        url "https://repo.lclpnet.work/repository/internal"
    }
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "notica" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }

    runs {
        named('server') {
            source 'testmod'
        }

        named('client') {
            source 'testmod'
        }
    }
}

sourceSets {
    api {}

    main {
        compileClasspath += api.getOutput()
        runtimeClasspath += api.getOutput()
    }

    client {
        compileClasspath += api.getOutput()
        runtimeClasspath += api.getOutput()
    }

    test {
        compileClasspath += client.getOutput() + api.getOutput()
        runtimeClasspath += client.getOutput() + api.getOutput()
    }

    testmod {
        compileClasspath += main.compileClasspath + main.getOutput() + client.compileClasspath + client.getOutput()
        runtimeClasspath += main.runtimeClasspath + main.getOutput() + client.runtimeClasspath + client.getOutput()
    }

    jmh {
        compileClasspath += api.getOutput() + client.getOutput()
        runtimeClasspath += api.getOutput() + client.getOutput()
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    include(modImplementation("work.lclpnet.mods.kibu:kibu-hooks:${project.kibu_hooks_version}"))
    include(modImplementation("work.lclpnet.mods.kibu:kibu-translation-api:${project.kibu_translation_api_version}"))
    include(modImplementation(apiImplementation("work.lclpnet.mods.kibu:kibu-hook-api:${project.kibu_hook_api_version}")))
    include(modImplementation("work.lclpnet.mods.kibu:kibu-access-lib:${project.kibu_access_lib_version}"))
    include(modImplementation("work.lclpnet.mods.kibu:kibu-networking-api:${project.kibu_networking_api_version}"))
    include(modImplementation('me.lucko:fabric-permissions-api:0.3.1'))

    include(implementation('org.json:json:20230227'))
    include(implementation('work.lclpnet:json-config4j:1.0.0'))

    apiImplementation(implementation('org.jetbrains:annotations:24.0.0'))

    testImplementation("work.lclpnet.mods.kibu:kibu-assets-api:${project.kibu_assets_api_version}")
    testImplementation("org.jcraft:jorbis:0.0.17")
    testImplementation "net.fabricmc:fabric-loader-junit:${project.loader_version}"
    testImplementation 'org.junit.jupiter:junit-jupiter-params:5.8.1'

    // must be defined for idea jmh plugin to execute benchmarks individually
    jmh 'org.openjdk.jmh:jmh-core:1.37'
    jmh 'org.openjdk.jmh:jmh-generator-bytecode:1.37'
    jmhAnnotationProcessor(jmh('org.openjdk.jmh:jmh-generator-annprocess:1.37'))
}

test {
    useJUnitPlatform()
}

afterEvaluate {
    configurations {
        testCompileClasspath.extendsFrom(minecraftCommonNamedCompile)
        testRuntimeClasspath.extendsFrom(minecraftCommonNamedRuntime)
        testCompileClasspath.extendsFrom(minecraftClientOnlyNamedCompile)
        testRuntimeClasspath.extendsFrom(minecraftClientOnlyNamedRuntime)
        testRuntimeClasspath.extendsFrom(modRuntimeClasspathClientMapped)
    }
}

[processResources, processTestmodResources].each {
    it.inputs.property "version", project.version

    it.filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
	it.options.release.set(21)
}

java {
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

[jar, sourcesJar].each {
	it.from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}

    it.from sourceSets.api.output
}

jmh {
    benchmarkMode = ['avgt', 'ss']
    fork = 2
    iterations = 5
    timeUnit = 'us'
    resultFormat = 'json'

    /* on linux, make sure to have:
     - the async-profiler library path on LD_LIBRARY_PATH (e.g. LD_LIBRARY_PATH=/opt/async-profiler/lib)
     - perf installed
     - expose kernel addresses for the current session (execute as root: echo 0 > /proc/sys/kernel/kptr_restrict)
     - enable perf events for unprivileged users (execute as root: echo 1 > /proc/sys/kernel/perf_event_paranoid)
     */
    profilers = ['async:dir=build/results/jmh/profiler;output=jfr']

    includeTests = true
    zip64 = true
}

jmhJar {
    from sourceSets.api.getOutput()
}

def jmhReportDir = project.file('build/reports/jmh')

jmhReport {
    jmhResultPath = project.file('build/results/jmh/results.json')
    jmhReportOutput = jmhReportDir
}

tasks.jmhReport.doFirst {
    jmhReportDir.mkdirs()
}

tasks.jmh.finalizedBy tasks.jmhReport

def env = System.getenv()

tasks.register("github", GithubDeploymentTask) {
    dependsOn tasks.remapJar

    config {
        token = env.get("GITHUB_TOKEN")
        repository = env.get("GITHUB_REPOSITORY")
    }

    release {
        title = "[$project.minecraft_version] Notica $project.version"
        tag = project.mod_version
    }

    assets.add(tasks.remapJar.archiveFile.get())
}

modrinth {
    token = env.get("MODRINTH_TOKEN")

    projectId = "notica"
    versionName = "[$project.minecraft_version] Notica $project.version"
    versionType = "release"
    uploadFile = remapJar

    dependencies {
        required.project "fabric-api"
    }
}

// configure the maven publication
publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = project.base.archivesName.get()

            from components.java

            pom {
                name = 'Notica'
                description = 'A fabric mod for playing .nbs files'
            }
        }
    }

    // automatically use DEPLOY_URL, DEPLOY_USER and DEPLOY_PASSWORD environment variables
    // or mavenHost, mavenUser and mavenPassword from props
    buildUtils.setupPublishRepository(repositories, props)
}