import org.apache.tools.ant.filters.ReplaceTokens
import work.lclpnet.build.task.GithubDeploymentTask

plugins {
    alias(libs.plugins.fabric.loom)
    alias(libs.plugins.maven.publish)
    alias(libs.plugins.gradle.build.utils)
    alias(libs.plugins.modrinth.minotaur)
    alias(libs.plugins.jmh)
    alias(libs.plugins.jmh.report)
    alias(libs.plugins.lombok)
}

Properties props = buildUtils.loadProperties('publish.properties')

version = "${project.mod_version}+${libs.versions.minecraft.get()}"
group = project.maven_group

def modId = project.mod_id
def javaVersion = libs.versions.java.get().toInteger()

base {
    archivesName = modId
}

repositories {
    maven {
        url "https://repo.lclpnet.work/repository/internal"
    }

    maven {
        url "https://repo.lclpnet.work/repository/snapshots"
    }

    // ModMenu
    maven {
        url "https://maven.terraformersmc.com/releases/"
    }

    // cloth-config
    maven {
        url "https://maven.shedaniel.me/"
    }
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "notica" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }

    runs {
        named("server") {
            source "testmod"
        }

        named("client") {
            source "testmod"
        }
    }
}

sourceSets {
    api {}

    main {
        compileClasspath += api.getOutput()
        runtimeClasspath += api.getOutput()
    }

    client {
        compileClasspath += api.getOutput()
        runtimeClasspath += api.getOutput()
    }

    test {
        compileClasspath += client.getOutput() + api.getOutput()
        runtimeClasspath += client.getOutput() + api.getOutput()
    }

    testmod {
        compileClasspath += main.compileClasspath + main.getOutput() + client.compileClasspath + client.getOutput()
        runtimeClasspath += main.runtimeClasspath + main.getOutput() + client.runtimeClasspath + client.getOutput()
    }

    jmh {
        compileClasspath += api.getOutput() + client.getOutput()
        runtimeClasspath += api.getOutput() + client.getOutput()
    }
}

dependencies {
    minecraft(libs.minecraft)
    implementation(libs.fabric.loader)
    implementation(libs.fabric.api)

    def includeImpl = { dep ->
        include(dep)
        implementation(dep)
    }

    includeImpl(libs.kibu.hooks)
    includeImpl(libs.kibu.translation.api)
    includeImpl(libs.kibu.hook.api)
    apiImplementation(libs.kibu.hook.api)
    includeImpl(libs.kibu.access.lib)
    includeImpl(libs.kibu.networking.api)
    includeImpl(libs.kibu.config.api)
    includeImpl(libs.permission.api)

    includeImpl(libs.json)
    includeImpl(libs.json.config4j)
    includeImpl(libs.night.config.core)
    includeImpl(libs.night.config.toml)

    compileOnlyApi(libs.cloth.config) {
        exclude(group: libs.fabric.api.get().group)
    }

    if (project.hasProperty("runtime_cloth_config")) localRuntime(libs.cloth.config)

    compileOnly(libs.modmenu)

    if (project.hasProperty("runtime_modmenu")) localRuntime(libs.modmenu)

    apiImplementation(libs.annotations)
    implementation(libs.annotations)

    testImplementation(libs.kibu.assets.api)
    testImplementation(libs.jorbis)
    testImplementation(libs.fabric.loader.junit)
    testImplementation(libs.junit.jupiter.params)
    testImplementation(libs.mockito.core)

    // must be defined for idea jmh plugin to execute benchmarks individually
    jmh(libs.jmh.core)
    jmh(libs.jmh.generator.bytecode)
    jmh(libs.jmh.generator.annprocess)
    jmhAnnotationProcessor(libs.jmh.generator.annprocess)
}

test {
    useJUnitPlatform()
}

afterEvaluate {
    configurations {
        testCompileClasspath.extendsFrom(minecraftCommonNamedCompile)
        testRuntimeClasspath.extendsFrom(minecraftCommonNamedRuntime)
        testCompileClasspath.extendsFrom(minecraftClientOnlyNamedCompile)
        testRuntimeClasspath.extendsFrom(minecraftClientOnlyNamedRuntime)
        testRuntimeClasspath.extendsFrom(modRuntimeClasspathClientMapped)
    }
}

[processResources, processTestmodResources].each {
    def tokens = [
            "version": project.version.toString(),
            "loader_version": libs.versions.fabric.loader.get(),
            "minecraft_compat": project.minecraft_compat,
            "java_version": javaVersion.toString()
    ]

    it.inputs.properties(tokens)

    it.filesMatching("fabric.mod.json") {
        expand(tokens)
    }

    it.filesMatching("*.mixins.json") {
        filter(ReplaceTokens, beginToken: '${', endToken: '}', tokens: tokens)
    }
}

tasks.withType(JavaCompile).configureEach {
	it.options.release.set(javaVersion)
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.toVersion(javaVersion)
    targetCompatibility = JavaVersion.toVersion(javaVersion)
}

[jar, sourcesJar].each {
	it.from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}

    it.from sourceSets.api.output
}

jmh {
    benchmarkMode = ['avgt', 'ss']
    fork = 2
    iterations = 5
    timeUnit = 'us'
    resultFormat = 'json'

    /* on linux, make sure to have:
     - the async-profiler library path on LD_LIBRARY_PATH (e.g. LD_LIBRARY_PATH=/opt/async-profiler/lib)
     - perf installed
     - expose kernel addresses for the current session (execute as root: echo 0 > /proc/sys/kernel/kptr_restrict)
     - enable perf events for unprivileged users (execute as root: echo 1 > /proc/sys/kernel/perf_event_paranoid)
     */
    profilers = ['async:dir=build/results/jmh/profiler;output=jfr']

    includeTests = true
    zip64 = true
}

jmhJar {
    from sourceSets.api.getOutput()
}

def jmhReportDir = project.file('build/reports/jmh')

jmhReport {
    jmhResultPath = project.file('build/results/jmh/results.json')
    jmhReportOutput = jmhReportDir
}

tasks.jmhReport.doFirst {
    jmhReportDir.mkdirs()
}

tasks.jmh.finalizedBy tasks.jmhReport

def env = System.getenv()

tasks.register("github", GithubDeploymentTask) {
    dependsOn tasks.jar

    config {
        token = env.get("GITHUB_TOKEN")
        repository = env.get("GITHUB_REPOSITORY")
    }

    release {
        title = "[${libs.versions.minecraft.get()}] Notica $project.version"
        tag = project.version
    }

    assets.add(tasks.jar.archiveFile.get())
}

modrinth {
    token = env.get("MODRINTH_TOKEN")

    projectId = "notica"
    versionName = "[${libs.versions.minecraft.get()}] Notica $project.version"
    versionType = "release"
    uploadFile = jar

    dependencies {
        required.project "fabric-api"
        required.project "cloth-config"
        optional.project "modmenu"
    }
}

// configure the maven publication
publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.base.archivesName.get()

            from components.java

            pom {
                name = 'Notica'
                description = 'A fabric mod for playing .nbs files'
            }
        }
    }

    // automatically use DEPLOY_URL, DEPLOY_USER and DEPLOY_PASSWORD environment variables
    // or mavenHost, mavenUser and mavenPassword from props
    buildUtils.setupPublishRepository(repositories, props)
}