# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.9
yarn_mappings=1.21.9+build.1
loader_version=0.17.2
loom_version=1.11-SNAPSHOT
mod_version=1.6.0

# Mod Properties
maven_group=work.lclpnet.mods
archives_base_name=notica

# Dependencies
fabric_version=0.133.14+1.21.9
kibu_hooks_version=0.62.0+1.21.9
kibu_hook_api_version=1.4.0
kibu_assets_api_version=0.1.0
kibu_translation_api_version=0.26.0+1.21.9
kibu_access_lib_version=0.17.0+1.21.9
kibu_networking_api_version=0.1.0+1.21.9
kibu_config_api_version=0.1.1
permission_api_version=0.4.1
cloth_config_version=20.0.148
modmenu_version=16.0.0-rc.1

runtime_modmenu=true
runtime_cloth_config=true
